apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "synapse-ai.fullname" . }}-config
  namespace: {{ include "synapse-ai.namespace" . }}
  labels:
    {{- include "synapse-ai.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ .Values.config | default "" | indent 4 }}
