apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "synapse-ai.fullname" . }}-extensions
  namespace: {{ include "synapse-ai.namespace" . }}
  labels:
    {{- include "synapse-ai.labels" . | nindent 4 }}
data:
  extensions_config.json: |
{{ .Values.extensionsConfig | default "" | indent 4 }}
