{{- if .Values.provisioner.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: provisioner
  namespace: {{ include "synapse-ai.namespace" . }}
  labels:
    {{- include "synapse-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: provisioner
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8002
      targetPort: http
  selector:
    {{- include "synapse-ai.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: provisioner
{{- end -}}
