{{- if and (not .Values.existingSecret) .Values.secrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "synapse-ai.providerSecret" . }}
  namespace: {{ include "synapse-ai.namespace" . }}
  labels:
    {{- include "synapse-ai.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $k, $v := .Values.secrets }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end -}}
